// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMlsVTwlJ0PonMYXvARLLZBWd_1vXyq90',
    appId: '1:697001739130:ios:609985371db51d765bccc3',
    messagingSenderId: '697001739130',
    projectId: 'simple-api-ecommerce',
    storageBucket: 'simple-api-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.cleanEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMlsVTwlJ0PonMYXvARLLZBWd_1vXyq90',
    appId: '1:697001739130:ios:609985371db51d765bccc3',
    messagingSenderId: '697001739130',
    projectId: 'simple-api-ecommerce',
    storageBucket: 'simple-api-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.cleanEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3C6zM9G2vkiiYfyXAUT4f_h0DNQDoVyo',
    appId: '1:697001739130:web:4c1106834374ea555bccc3',
    messagingSenderId: '697001739130',
    projectId: 'simple-api-ecommerce',
    authDomain: 'simple-api-ecommerce.firebaseapp.com',
    storageBucket: 'simple-api-ecommerce.firebasestorage.app',
    measurementId: 'G-JE6PDNTQ16',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3C6zM9G2vkiiYfyXAUT4f_h0DNQDoVyo',
    appId: '1:697001739130:web:4c1106834374ea555bccc3',
    messagingSenderId: '697001739130',
    projectId: 'simple-api-ecommerce',
    authDomain: 'simple-api-ecommerce.firebaseapp.com',
    storageBucket: 'simple-api-ecommerce.firebasestorage.app',
    measurementId: 'G-JE6PDNTQ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzYciV1M-XRAmS-zyvQJCh9MhTqS5ydd8',
    appId: '1:697001739130:android:6dd9f204bdc4a6e15bccc3',
    messagingSenderId: '697001739130',
    projectId: 'simple-api-ecommerce',
    storageBucket: 'simple-api-ecommerce.firebasestorage.app',
  );

}